version: '3.8'

services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: myuser
            MONGO_INITDB_ROOT_PASSWORD: mypassword
        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express:latest
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: myuser
            ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword  
            ME_CONFIG_MONGODB_SERVER: mongodb    
        ports:
            - 8081:8081


    flaskapp:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
